apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-8k7f
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-8k7f@sha256:4704cb4d04014b6ffb6295941487fee486169c8a802b7a154a84d80147b14b4e
        name: my-python
        resources: {}
status: {}
