apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-r4i0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-r4i0@sha256:b821ca455b5f6895a48b78c62e32ccc5da01969abdc435548471f9f10759653c
        name: my-nodejs
        resources: {}
status: {}
